services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: python-selenium-hub
    ports:
      - "4444:4444"

  firefox-node:
    image: selenium/node-firefox:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      # This extracts the videos from the container to local machine
      - ./videos:/videos:z
      - ./videos:/opt/selenium/assets:z